### PR TITLE
Spark s2i

### PR DESCRIPTION
**Pull request by lulf**
@ppatierno I came across the oshinko-s2i which allows you to build the java app + deploy the spark cluster in one go. Since we have to create one cluster per app, maybe this is the simplest and easiest way?

Don't try to run it yet BTW, there are still some issues, but just wondering if you'd like the general idea.

### CODE REVIEW

**Comment by ppatierno** [comment]
@lulf on one side I really like the idea with this simplification but at same time I think that people, who don't know about Apache Spark, won't get that a Spark cluster and a Spark driver are two separate things and we are using S2I for deploying them all together. But at same time : do we need people to really understand it ? :-)

**Comment by lulf** [comment]
I don't think that understanding spark should be needed/is the purpose of this workshop, which is why I'd like to simplify it.

**Comment by ppatierno** [comment]
@lulf then +1 ! ;) Let me know when it's finished and ready to be merged so that I can review it deeply.

**Comment by lulf** [comment]
@ppatierno So after experimenting a bit with this today I'm not sure I'm as positive as I was initially. I think perhaps a nice compromise here is to provide some sort of template to do the oshinko create thing. I've been trying to create a docker image + a kubernetes job that can deploy the oshinko cluster, but I'm getting some errors in the docker image unfortunately.

**Comment by ppatierno** [comment]
@lulf we don't need to do that. I think that deploying the spark cluster first and the driver after that involves just a couple of commands. Maybe too late to invest time in new stuff, better to test and retest what we already have working :)

**Comment by lulf** [comment]
@ppatierno You are right, we should do that :) My only worry is that the oshinko command only runs on linux, in which case it gets a bit complicated to provision. We can do it on-demand for users wanting to do the workshop perhaps?

I will close this PR then and instead update the steps with more figures describing each step etc. Wdyt?

**Pull request closed without merging**
